version: '3.3'
services:
  k6:
    image: grafana/k6@sha256:cf680d4f4251220743021bc6ae2b246679f47a986bd7468f3f25d2013f327495
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - SUBSCRIPTION_KEY=${sub_key}
      - VARS=/env/${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
      - K6_INSECURE_SKIP_TLS_VERIFY=true
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx@sha256:6784fb0834aa7dbbe12e3d7471e69c290df3e6ba810dc38b34ae33d3c1c05f7d
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

