version: '3.8'

services:
  app:
    container_name: 'pagopa-anonymizer'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
    env_file:
      - ./.env
    ports:
      - "3000:3000"
