microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: "pagopa-anonymizer"
  image:
    repository: ghcr.io/pagopa/pagopa-anonymizer
    tag: "0.2.2-24-PAGOPA-3137-setup-logging-kibana"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /info
      port: 3000
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 3000
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  serviceMonitor:
    create: false
  ports:
    - 3000 #http
  service:
    create: true
    type: ClusterIP
    ports:
      - 3000 #http
  ingress:
    create: true
    host: "weuprod.shared.internal.platform.pagopa.it"
    path: /pagopa-anonymizer/(.*)
    servicePort: 3000
  serviceAccount:
    name: "shared-workload-identity"
  azure:
    workloadIdentityClientId: "152e401f-314d-4be1-9510-c74d27997cbc"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "3Gi"
      cpu: "0.25"
    limits:
      memory: "6Gi"
      cpu: "0.50"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 120 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENV: "prod"
    WEBSITE_SITE_NAME: "pagopa-anonymizer" # required to show cloud role name in application insights
    APP_LOGGING_LEVEL: 'INFO'
  envSecret:
    APPLICATION_INSIGHTS_CONNECTION_STRING: ai-p-connection-string
  keyvault:
    name: "pagopa-p-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-anonymizer
        tag: "0.0.1"
        pullPolicy: Always
      envConfig:
      envSecret:
