microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-anonymizer
    tag: "0.0.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /info
      port: 5000
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 5000
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: false
  ports:
    - 5000 #http
  service:
    type: ClusterIP
    ports:
      - 5000 #http
  ingress:
    create: true
    host: "weuprod.shared.internal.platform.pagopa.it"
    path: /pagopa-anonymizer/(.*)
    servicePort: 5000
  serviceAccount:
    name: "shared-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "768Mi"
      cpu: "0.50"
  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 120 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENV: "prod"
    WEBSITE_SITE_NAME: "pagopaanonymizer" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "python"
  keyvault:
    name: "pagopa-p-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-anonymizer
        tag: "0.0.1"
        pullPolicy: Always
      envConfig:
      envSecret:
