italian_toponym = [
    "Via",
    "Viale",
    "Corso",
    "Strada",
    "Stradone",
    "Circonvallazione",
    "Piazzale",
    "Piazza",
    "Piazzetta",
    "Largo",
    "Rotonda",
    "Vicolo",
    "Traversa",
    "Rampa",
    "Salita",
    "Discesa",
    "Spalto",
    "Passeggiata",
    "Località",
    "Contrada",
    "Ruga",
    "Rio Terà",
    "Salizada",
    "Fondamenta",
    "Calle",
    "Campo",
    "Sottoportego",
    "Corticella",
    "Chiasso",
    "Angiporto"
]  # Context words in Italian